### ISSUE TITLE
Jorodox is No Longer Supported on the Current Version of Chrome.

### ISSUE THREAD

**Issue by Magpie490** [DaanBroekhof/JoroDox#5]
Hello, Developer of Jorodox your tool has been invaluable for paradox modding over the past few years but starting in March your tool has been rendered unrunnable by Google please find a way to fix it if you can and have time we simply cannot create new models without it.

**Comment by Harain** [comment]
yea, would really appreciate a version that runs outside Chrome

**Comment by Olaf1980** [comment]
Dear Developer, it would be great, if you could found a solution. It was the perfect extension...

**Comment by flintsparc** [comment]
It is the handiest tool I've yet found for quickly browsing Paradox meshes.

**Comment by DaanBroekhof** [comment]
I have updated the extension to conform to the changed Google Chrome extension requirements. Mainly changed how it accessed the file system.

The new version is uploaded for review to Google, which says it might take some weeks to update. 
Hopefully it will be faster than that. 😄 

(in the mean time, you could download this github repository and run it as an 'unpacked extension' see - https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/)

**Comment by flintsparc** [comment]
You are a hero of the people, DaanBroekhof!

**Comment by DaanBroekhof** [comment]
The extension is now compatible again with the latest google chrome, and approved by Google.

The new version is 0.8.1 - to open it, you no longer access `chrome://apps` (this was discontinued by Google)
Instead you have to enable it, 'pin' it in your toolbar, and then click the icon. 

Which is a bit annoying, but was the fastest way to get things functional again.

**Comment by Olaf1980** [comment]
You are my hero! Thanks, without you, i havent my favourite ships in Stellaris!!
